### ISSUE TITLE
Earth Science Data Category

### ISSUE THREAD

**Issue by predam1** [geological-survey-of-queensland/vocabularies#246]
I suggest removing the following from earth science data
- atmospheric sciences
- biological sciences + ecology
- demography

**Comment by KellyVance** [comment]
I have created a collection of terms for the lodgement portal so none of these will be selectable for future report submission, and for the most part they will be invisible in the system.

But they are in there because of past reports in QDEX Reports that had related keywords. I don't know why, but they are in there somehow.
14 reports relating to Atmospheric Science
13 for biological sciences + ecology
and even 3 for demography

They may become increasingly more relevant in the future so I'd rather preserve them but keep them hidden for now.

**Comment by predam1** [comment]
Thanks Vance. I had no idea.

**Comment by KellyVance** [comment]
I'm now closing this issue. If there are any objections I can reopen.

**Comment by predam1** [comment]
Did you actually see the reports? I had a similar problem when I did some work for John. There were no reports associated with some keywords he was looking to define. 
In any case, it's minor for the moment.
