### ISSUE TITLE
Addition to commodities vocabs

### ISSUE THREAD

**Issue by talebib** [geological-survey-of-queensland/vocabularies#260]
Please add following commodities into the vocabs:

1. Geothermal
2. Carbon geostorage / sequestration.

Thank you.

**Comment by KellyVance** [comment]
Good additions
having a look myself I also notice Water is missing as a commodity
I suggest we put in a concept of energy resources for non-material commodities that use the energy directly and include Geothermal, Solar, Wind and Hydro. 
Also a top concept of Sequestered Commodities for resources that become a commodity when captured, sequestered, or disposed of rather than extracted. Then (for now) just add a single child concept for GHG.. We can add more later if it becomes a thing.

**Comment by SalEdwards01** [comment]
Hi Vance,
 some further additions and amendments to the commodities vocab.

Matt G has asked for **prospecting**  to be added to the vocab for the situations where the is no actual target being explored for.

Micalea has pointed out that the American term Coal bed methane is used int he vocab rather than **coal seam gas**

Micaela has also pointed out that **petroleum** is missing from the vocab, but I think it's covered by the other gaseous hydrocarbons, gas hydrates, oil etc that are in the vocab already. Petroleum is too broad a label for a commodity, unless people want tobe lazy.

I have noticed that we have oil shale in the vocab, but do we need shale oil and shale gas, if not there (sorry, if it's there, I can't see the full vocab list).

Also, should the commodities have a capital letter at the start of their names rather than being all lower case?

Thanks
Sal

**Comment by SalEdwards01** [comment]
Yes, I meant to add water, but forgot!
Good pick up :-)

**Comment by KellyVance** [comment]
> Hi Vance,
> some further additions and amendments to the commodities vocab.
> 
> Matt G has asked for **prospecting** to be added to the vocab for the situations where the is no actual target being explored for. _prospecting isn't a commodity, a null entry would be more correct. We may need a sytem rule change for certain circumstances where a commodity doesn't need to be specified._
> 
> Micalea has pointed out that the American term Coal bed methane is used int he vocab rather than **coal seam gas** _I will swap labels to display Australian term Coal Seam Gas as preferred_
> 
> Micaela has also pointed out that **petroleum** is missing from the vocab, but I think it's covered by the other gaseous hydrocarbons, gas hydrates, oil etc that are in the vocab already. Petroleum is too broad a label for a commodity, unless people want to be lazy. _Petroleum is an alias for oil... not perfect, i know. But i think its fine for the purposes here._
> 
> I have noticed that we have oil shale in the vocab, but do we need shale oil and shale gas, if not there (sorry, if it's there, I can't see the full vocab list). _shale oil and shale gas are definitely missing. While I add some of these other terms to the vocabulary can you please reply with some appropriate definitions for me to copy and paste?_
> 
> Also, should the commodities have a capital letter at the start of their names rather than being all lower case? _Yes. It's an inherited issue from the source material. I'll get around to fixing it at some point, but at the moment it is a lot of time to fix an issue that isn't breaking anything._
> 
> Thanks
> Sal

Hi @SalEdwards01 replies embedded in italics above.

**Comment by SalEdwards01** [comment]
Adding a commodity is mandatory, so can't have a null entry in Lodgement Portal reports. 

Petroleum I don't understand are you adding it or going with my comment, that it's covered?

OK, I'll find some definitions for sale oil and shale gas and provide.

**Comment by SalEdwards01** [comment]
shale gas definition and source
https://www.glossary.oilfield.slb.com/en/Terms/s/shale_gas.aspx

shale oil definition and source
https://www.glossary.oilfield.slb.com/en/Terms/s/shale_oil.aspx

gas shale definition and source (more detailed than def given for shale gas, you pick which is best)
https://www.glossary.oilfield.slb.com/Terms/g/gas_shale.aspx

**Comment by KellyVance** [comment]
I agree that Petroleum is already covered.
I'll add an _undefined_ concept. But this is not a great solution. In the future we will need to do the more difficult, but more robust system change to the rule set and remove this concept.

**Comment by talebib** [comment]
Thanks Vance.
All good now.
