### ISSUE TITLE
The Concept list for BoreHole Pupose contains duplicate terms and doesn't link to the definitions

### ISSUE THREAD

**Issue by lisa-woody** [geological-survey-of-queensland/vocabularies#297]
https://vocabs.gsq.digital/vocabulary/borehole-purpose/concept/

![image](https://user-images.githubusercontent.com/65147781/88002760-a08d8580-cb46-11ea-9af6-03bf3349d119.png)

**Comment by KellyVance** [comment]
@lisa-woody the vocabulary file is properly formed and formatted. 
I can see the same issue in vocPrez in all the vocabularies I have just checked. The standard display is fine but the endpoint shows duplicates. Something is going awry in the endpoint process for VocPrez @DavidCrosswellGSQ

**Comment by DavidCrosswellGSQ** [comment]
Two issues here:
1. There is a known bug in VocPrez that has been fixed in Version 2 of VocPrez. We will upgrade to VocPrez2 post go-live August 3 (version 1 works) - apart from these types of visual issues.

2. The links for these don't work as this vocab is not published in linked.data.gov.au - Nick was meant to get all registered and approved, but there are a number of vocabs that aren't registered.
