### ISSUE TITLE
Missing Permits

### ISSUE THREAD

**Issue by lisa-woody** [geological-survey-of-queensland/vocabularies#300]
- GHG is not available in the list of Permit Types

**Comment by KellyVance** [comment]
@lisa-woody perhaps people are referring to them by informal names, because they are definitely in there.

[Exploration Permit Greenhouse Gas (EPQ)](https://vocabs.gsq.digital/object?vocab_id=qld-resource-permit&uri=http%3A//linked.data.gov.au/def/qld-resource-permit/ExplorationPermitGreenhouseGas)

[Greenhouse Gas Lease (QL)](https://vocabs.gsq.digital/object?vocab_id=qld-resource-permit&uri=http%3A//linked.data.gov.au/def/qld-resource-permit/GreenhouseGasLease)
